server:
  servlet:
    context-path: /api/ds
  port: @port@


spring:
  application:
    name: gofine-dataSite
  redis:
      host: @redis.host@
      port: @redis.port@
  datasource:
    url: @mysql.jdbc.url@
    username: @mysql.jdbc.username@
    password: @mysql.jdbc.password@
    driver-class-name: @driverclass@
    maxActive: 2
    initialSize: 1

mybatis:
   mapper-locations: classpath:mapping/*.xml
